# Generated by Django 5.1.7 on 2025-04-03 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_nickname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
