# Generated by Django 5.1.7 on 2025-04-26 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='user',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='track',
            name='user',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
    ]
